notifications:
  email: false

language: android
jdk: oraclejdk8

env:
  matrix:
    - API=android-27 ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-27.0.1
    - android-27
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-27
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean assemble test

after_success:
  - ./gradlew :library:jacocoTestReport :library:coveralls
